// packages/solid/src/CrudTable.tsx
import { For, Show } from 'solid-js';
import type { Component } from 'solid-js';
import type { FieldMeta } from '@faster-crud/core';
import type { CrudStoreReturn } from './createCrudStore';

export interface CrudTableProps<T = any> {
  store: CrudStoreReturn<T>;
  onEdit?: (item: T) => void;
  idKey?: string;
}

function isVisibleInList(field: FieldMeta): boolean {
  if (field.ignore) return false;
  if (field.hidden?.includes('list')) return false;
  return true;
}

export function CrudTable<T extends Record<string, any>>(props: CrudTableProps<T>) {
  const fields = () => {
    const m = props.store.meta();
    return m ? Object.values(m.fields).filter(isVisibleInList) : [];
  };

  const totalPages = () => Math.ceil(props.store.total() / props.store.page().size);

  const handleSort = (field: FieldMeta) => {
    if (!field.list?.sortable) return;
    const s = props.store.sort();
    if (s?.field === field.key) {
      props.store.setSort(s.order === 'asc' ? { field: field.key, order: 'desc' } : null);
    } else {
      props.store.setSort({ field: field.key, order: 'asc' });
    }
  };

  const idKey = () => props.idKey ?? 'id';

  return (
    <div>
      <Show when={props.store.loading()}>
        <div>Loading...</div>
      </Show>
      <Show when={props.store.meta()}>
        <table>
          <thead>
            <tr>
              <For each={fields()}>
                {(f) => (
                  <th
                    onClick={() => handleSort(f)}
                    style={f.list?.sortable ? { cursor: 'pointer' } : undefined}
                  >
                    {f.label || f.key}
                    {props.store.sort()?.field === f.key &&
                      (props.store.sort()!.order === 'asc' ? ' ↑' : ' ↓')}
                  </th>
                )}
              </For>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <For each={props.store.data()}>
              {(item) => (
                <tr>
                  <For each={fields()}>
                    {(f) => <td>{String((item as any)[f.key] ?? '')}</td>}
                  </For>
                  <td>
                    <Show when={props.onEdit && props.store.meta()!.operations.includes('update')}>
                      <button type="button" onClick={() => props.onEdit!(item)}>
                        Edit
                      </button>
                    </Show>
                    <Show when={props.store.meta()!.operations.includes('remove')}>
                      <button type="button" onClick={() => props.store.remove((item as any)[idKey()])}>
                        Delete
                      </button>
                    </Show>
                  </td>
                </tr>
              )}
            </For>
          </tbody>
        </table>
        <Show when={totalPages() > 1}>
          <div>
            <button
              type="button"
              disabled={props.store.page().current <= 1}
              onClick={() =>
                props.store.setPage({
                  ...props.store.page(),
                  current: props.store.page().current - 1,
                })
              }
            >
              Prev
            </button>
            <span>
              {' '}
              {props.store.page().current} / {totalPages()}{' '}
            </span>
            <button
              type="button"
              disabled={props.store.page().current >= totalPages()}
              onClick={() =>
                props.store.setPage({
                  ...props.store.page(),
                  current: props.store.page().current + 1,
                })
              }
            >
              Next
            </button>
          </div>
        </Show>
      </Show>
    </div>
  );
}

// packages/svelte/src/CrudTable.svelte
<script lang="ts">
  import type { CrudStore } from './store';
  import type { FieldMeta } from '@faster-crud/core';

  interface Props {
    store: CrudStore<any>;
    onEdit?: (item: any) => void;
    idKey?: string;
  }

  let { store, onEdit, idKey = 'id' }: Props = $props();

  function isVisibleInList(field: FieldMeta): boolean {
    if (field.ignore) return false;
    if (field.hidden?.includes('list')) return false;
    return true;
  }

  let fields = $derived(
    store.meta ? Object.values(store.meta.fields).filter(isVisibleInList) : []
  );
  let totalPages = $derived(Math.ceil(store.total / store.page.size));

  function handleSort(field: FieldMeta) {
    if (!field.list?.sortable) return;
    if (store.sort?.field === field.key) {
      store.sort = store.sort.order === 'asc'
        ? { field: field.key, order: 'desc' }
        : null;
    } else {
      store.sort = { field: field.key, order: 'asc' };
    }
  }

  function prevPage() {
    store.page = { ...store.page, current: store.page.current - 1 };
  }

  function nextPage() {
    store.page = { ...store.page, current: store.page.current + 1 };
  }

  function handleDelete(item: any) {
    store.remove(item[idKey]);
  }
</script>

{#if store.meta}
  {#if store.loading}
    <div>Loading...</div>
  {/if}

  <table>
    <thead>
      <tr>
        {#each fields as f}
          <th
            onclick={() => handleSort(f)}
            style={f.list?.sortable ? 'cursor: pointer' : ''}
          >
            {f.label || f.key}
            {#if store.sort?.field === f.key}
              {store.sort.order === 'asc' ? ' ↑' : ' ↓'}
            {/if}
          </th>
        {/each}
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {#each store.data as item, i (item[idKey] ?? i)}
        <tr>
          {#each fields as f}
            <td>{String(item[f.key] ?? '')}</td>
          {/each}
          <td>
            {#if onEdit && store.meta.operations.includes('update')}
              <button type="button" onclick={() => onEdit?.(item)}>Edit</button>
            {/if}
            {#if store.meta.operations.includes('remove')}
              <button type="button" onclick={() => handleDelete(item)}>Delete</button>
            {/if}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>

  {#if totalPages > 1}
    <div>
      <button type="button" disabled={store.page.current <= 1} onclick={prevPage}>
        Prev
      </button>
      <span> {store.page.current} / {totalPages} </span>
      <button type="button" disabled={store.page.current >= totalPages} onclick={nextPage}>
        Next
      </button>
    </div>
  {/if}
{/if}
